print('Hello There! What is your name? ')
Name = input()
print('Nice to meet you!',Name)
print('How old are you?')
age = input()
birth_year = 2023-int(age)
print(birth_year,'is your birth year')
answer  = str(birth_year)
print('You are born in',answer)